GET http://localhost/rplbk-tugas2/api/product/read.php

###
POST http://localhost/rplbk-tugas2/api/product/create.php
content-type: application/json

{
    "name" : "Bantal",
    "description" : "The best pillow for amazing programmers.",
    "category_id" : 2,
    "created" : "2018-06-01 00:35:07"
}

###
GET http://localhost/rplbk-tugas2/api/product/read_one.php?id=106

###
POST http://localhost/rplbk-tugas2/api/product/update.php
content-type: application/json

{
    "id" : "106",
    "name" : "Amazing Pillow 3.0",
    "price" : "255",
    "description" : "The best pillow for amazing programmers.",
    "category_id" : 2,
    "created" : "2018-08-01 00:35:07"
}

###
POST http://localhost/rplbk-tugas2/api/product/delete.php
content-type: application/json

{
    "id" : "106"
}

###
GET http://localhost/rplbk-tugas2/api/product/search.php?s=shirt

###
GET http://localhost/rplbk-tugas2/api/product/read_paging.php

###
GET http://localhost/rplbk-tugas2/api/category/read.php